In [ ]:
# pip install 'kagglehub[pandas-datasets]'

Defaulting to user installation because normal site-packages is not writeable
Collecting kagglehub[pandas-datasets]
  Downloading kagglehub-0.3.13-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from kagglehub[pandas-datasets]) (25.0)
Collecting pyyaml (from kagglehub[pandas-datasets])
  Downloading pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from kagglehub[pandas-datasets]) (2.32.5)
Collecting tqdm (from kagglehub[pandas-datasets])
  Downloading tqdm-4.68.4-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: pandas in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from kagglehub[pandas-datasets]) (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub[pandas-datasets]) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub[pandas-datasets]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub[pandas-datasets]) (2025.10.5)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.15.0)
Downloading kagglehub-0.3.13-py3-none-any.whl (68 kB)
Downloading pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl (174 kB)
Downloading tqdm-4.68.4-py3-none-any.whl (676 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.6/676.6 kB 113.3 kB/s eta 0:00:00 0:00:01
Installing collected packages: tqdm, pyyaml, kagglehub
Successfully installed kagglehub-0.3.13 pyyaml-6.0.3 tqdm-4.68.4

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import kagglehub

# First-time only: authenticates with Kaggle (opens a browser login,
# then caches the token locally so you won't need to do this again).
# kagglehub.login()

/Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from kagglehub import KaggleDatasetAdapter

# The dataset contains a single file:
file_path = "fifa_world_cup_2026_player_performance.csv"

df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset",
    file_path,
)

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.2).

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

In [5]:
df.isnull().sum()

player_id                   0
player_name                 0
age                         0
nationality                 0
team                        0
                           ..
total_goals_tournament      0
total_assists_tournament    0
total_minutes_tournament    0
player_of_match_awards      0
tournament_rating           0
Length: 75, dtype: int64

In [6]:
df.describe(include='all')

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
count,54600,54600,54600.000000,54600,54600,54600.000000,54600,54600.000000,54600.000000,54600,...,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000
unique,1248,1245,NaN,48,48,NaN,4,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,P00960,Pierre-Emile Christensen,NaN,Qatari,Qatar,NaN,Defender,NaN,NaN,Right,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,66,86,NaN,1716,1716,NaN,18900,NaN,NaN,40656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,26.296484,NaN,NaN,13.500000,NaN,181.654341,75.754853,NaN,...,2.850165,60.318379,46.135778,63.750396,55.572154,0.643993,0.607601,272.300311,0.030659,3.634046
std,NaN,NaN,4.067519,NaN,NaN,7.500069,NaN,6.277792,3.951481,NaN,...,4.228436,20.234988,22.424337,19.860028,13.661343,1.093781,0.931527,116.806184,0.206520,3.163411
min,NaN,NaN,17.000000,NaN,NaN,1.000000,NaN,163.000000,65.000000,NaN,...,0.000000,15.000000,5.000000,25.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,23.000000,NaN,NaN,7.000000,NaN,177.000000,73.000000,NaN,...,0.000000,43.700000,29.800000,46.500000,46.400000,0.000000,0.000000,184.000000,0.000000,0.000000
50%,NaN,NaN,26.000000,NaN,NaN,13.500000,NaN,182.000000,76.000000,NaN,...,1.100000,57.000000,40.500000,61.100000,55.000000,0.000000,0.000000,268.000000,0.000000,5.400000
75%,NaN,NaN,29.000000,NaN,NaN,20.000000,NaN,186.000000,78.000000,NaN,...,4.000000,75.100000,59.000000,78.900000,63.900000,1.000000,1.000000,359.000000,0.000000,6.400000
max,NaN,NaN,39.000000,NaN,NaN,26.000000,NaN,200.000000,87.000000,NaN,...,37.000000,99.000000,99.000000,99.000000,99.000000,10.000000,8.000000,615.000000,4.000000,9.500000

In [7]:
df[df['age']>38]

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
882,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,97.3,13.5,99.0,54.7,0,0,257,0,0.0
1924,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,5.4,99.0,16.2,99.0,84.8,0,0,178,0,6.6
2782,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,3.0,81.7,40.6,99.0,63.5,0,0,415,0,6.8
3066,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,73.7,26.2,99.0,50.4,0,0,181,0,0.0
3198,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,4.6,99.0,15.8,99.0,66.9,0,0,403,0,6.6
3769,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,91.0,35.1,99.0,35.7,0,0,281,0,0.0
4678,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,34.3,99.0,42.5,0,0,54,0,0.0
6578,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,4.8,99.0,26.0,93.0,43.5,0,0,192,0,6.6
6707,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,30.0,99.0,65.0,0,0,417,0,0.0
7227,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,32.3,99.0,40.2,0,0,96,0,0.0
9724,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,7.7,99.0,43.7,99.0,53.5,0,0,276,0,7.5
9878,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,33.7,99.0,64.7,0,0,85,0,0.0
10321,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,46.7,39.3,99.0,42.4,0,0,145,0,0.0
11102,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,6.0,99.0,33.4,99.0,65.0,0,0,254,0,6.9
14117,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,30.5,99.0,60.0,0,0,325,0,0.0
14663,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,89.3,34.1,99.0,64.5,0,0,37,0,0.0
14922,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,20.4,99.0,53.8,0,0,314,0,0.0
15546,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,56.3,36.3,99.0,70.9,0,0,219,0,0.0
17549,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,69.0,29.3,99.0,65.0,0,0,242,0,0.0
21814,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,5.1,79.1,26.4,99.0,64.5,0,0,214,0,6.5
22151,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,49.2,99.0,55.9,0,0,257,0,0.0
24570,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,5.3,78.2,27.4,99.0,78.8,0,0,414,0,6.8
27560,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,3.2,99.0,38.8,99.0,57.3,0,0,260,0,6.4
32524,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,94.3,36.2,88.6,51.4,0,0,390,0,0.0
33462,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,4.0,78.8,42.8,99.0,58.5,0,0,404,0,6.4
35723,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,45.7,99.0,63.2,0,0,114,0,0.0
36165,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,48.9,99.0,47.8,0,0,262,0,0.0
39102,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,95.6,12.1,99.0,49.0,0,0,118,0,0.0
40222,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,7.1,99.0,30.9,99.0,54.7,0,0,400,0,7.8
46486,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,26.7,74.3,85.7,0,0,281,0,0.0
46928,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,49.7,99.0,88.5,0,0,251,0,0.0
47267,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,31.0,99.0,96.6,0,0,266,0,0.0
48490,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,4.2,88.7,58.0,99.0,99.0,0,0,171,0,7.4
48828,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,5.8,99.0,26.6,99.0,99.0,0,0,297,0,6.0
49088,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,5.5,74.2,31.6,99.0,99.0,0,0,242,0,7.3
50646,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,41.2,99.0,94.2,0,0,388,0,0.0
52025,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,99.0,14.6,99.0,57.8,0,0,264,0,0.0
54416,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,...,0.0,54.6,33.7,99.0,99.0,0,0,105,0,0.0

In [8]:
df['player_id'].nunique()

1248

In [9]:
df.shape

(54600, 75)

In [10]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.groupby('team')['player_name']

In [16]:
df.duplicated(subset=['player_id', 'match_id']).sum()

np.int64(0)